### ISSUE TITLE
Wrong URL to Lumbras Giga Base

### ISSUE THREAD

**Issue by Lumbra74** [nloding/chess-resources#1]
The URL for LumbrasGigaBase has changed. It is now https://lumbrasgigabase.com/

**Comment by nloding** [comment]
Thanks @Lumbra74 - I fixed it in in this months update! In other news, I want to make this website better and share it wider in the coming months. If you have any suggestions on improvements, let me know (I threw this together in an hour or two), and feel free to share!

**Comment by Lumbra74** [comment]
No, I don‘t have any ideas. I‘m still trying to push the ranking of my site, but I‘m struggling a bit with that.Generally, it is not easy to get recognition in the chess world. There are a few sites, as ugly as they are, which are well known and used by many people. The chess folks don‘t like to change their habits… 😂Am 25.10.2024 um 23:00 schrieb Nathan Loding ***@***.***>:﻿
Thanks @Lumbra74 - I fixed it in in this months update! In other news, I want to make this website better and share it wider in the coming months. If you have any suggestions on improvements, let me know (I threw this together in an hour or two), and feel free to share!
